[package]
name = "assetparty-notify"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
thirtyfour = "0.30"
log = "0.4.0"
env_logger = "0.9"
ctrlc = "3.2"
